### PR TITLE
Readme Updated

### PR DESCRIPTION
**Pull request by m8**
readme updated, screenshot added, build instructions added, license details added.

### CODE REVIEW

**Comment by clefebvre** [comment]
Use shadow tag for the screenshot.
In the build section, you need to let people know how to install dependencies. mkbuild-dep or something like that...

**Comment by m8** [comment]
Thanks for the feedback @clefebvre, I added `dpkg-checkbuilddeps` for checking dependencies but if you want I can replace with `mkbuild-dep`. Also, I had opened PR for some other readmes, I will update these projects according to the your feedback.

**Review by hsbasu — COMMENTED** [review]
It's a really useful software to linux users especially for beginners like me. Please add a separate section for its features. For example:

Features:
1. Allow users to backup user data as tar balls
2. Backup manually installed `apt` packages and `flatpaks`

**Comment by m8** [comment]
@clefebvre could you check other PR's also, it would be nice to have screenshots in projects:
https://github.com/linuxmint/mintdesktop/pull/46
https://github.com/linuxmint/mintinstall/pull/310
https://github.com/linuxmint/mintstick/pull/88

**Pull request merged**
